version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./novels:/app/novels
  #     - ./scripts:/app/scripts
  #   environment:
  #     WEAVIATE_URL: "http://192.168.1.11:8080"
  #     LLM_URL: "http://192.168.1.11:5000"
  #   deploy:
  #     resources:
  #       reservations:
  #         memory: 4G

  weaviate-importer:
    image: weaviate-importer:latest
    build:
      context: .
      dockerfile: Dockerfile.import
    environment:
      - WEAVIATE_URL=http://192.168.1.11:8080
      - DATA_PATH=/app/texts_processed
    volumes:
      - ./texts_processed:/app/texts_processed
    restart: on-failure
    command: python weaviate_importer.py