version: '3.8'

services:
  weaviate-importer:
    image: weaviate-importer:latest
    build:
      context: .
      dockerfile: Dockerfile.import
    environment:
      - WEAVIATE_HTTP_HOST=192.168.1.11
      - WEAVIATE_HTTP_PORT=8080
      - WEAVIATE_GRPC_HOST=192.168.1.11
      - WEAVIATE_GRPC_PORT=50051
      - DATA_PATH=/app/texts_processed
    volumes:
      - ./texts_processed:/app/texts_processed
    # restart: on-failure
    command: tail -f /dev/null
    # command: python weaviate_importer.py
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8001:8080"
    volumes:
      - ./webdata:/app/backend/data
    # environment:
    #   - OLLAMA_API_BASE=http://192.168.1.11:11434
    restart: unless-stopped