version: '3.8'

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      # gRPC configuration
      GRPC_PORT: "50051"
    networks:
      - rag_network

  ollama:
    container_name: ollama
    image: ollama
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434" 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    volumes:
      - /home/way/Workspace/ollama/models:/models
    restart: always
    networks:
      - rag_network

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    image: rag_proxy
    ports:
      - "8000:8000"
    environment:
      - WEAVIATE_HTTP_HOST=weaviate
      - WEAVIATE_HTTP_PORT=8080
      - WEAVIATE_GRPC_HOST=weaviate
      - WEAVIATE_GRPC_PORT=50051
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - weaviate
      - ollama
    networks:
      - rag_network
    restart: unless-stopped
  
networks:
  rag_network:
    driver: bridge
  